config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/posts/search', to: 'posts#search'
  resources :posts do
    resources :comments
  end

  get '/admin', to: 'admin#index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { where(deleted: false) }
  belongs_to :user
  has_many :comments, dependent: :destroy

  # Calculate the score of the post for the purpose of selecting trending posts
  # formula is log_10(activities) + sign * (submission_time - epoch)/45000
  # where activities = max{number of likes + number of comments, 1},
  # epoch = 1970/1/1, time difference is in seconds,
  # sign = 1 if there is at least one like or comment, and 0 otherwise
  def compute_trending_score
    # TODO(ajyang99) replace 5 with the actual number of likes once like
    # functionality is implemented
    mock_num_likes = 5
    num_activities = mock_num_likes + comments.length
    sign = num_activities > 0 ? 1 : 0
    num_activities = [num_activities, 1].max
    seconds_since_epoch = created_at.to_i
    # post fresher by 12.5h (45000s) equiv to older post with 10x activities
    freshness_coefficient = 45_000
    Math.log10(num_activities) +
      sign * seconds_since_epoch / freshness_coefficient
  end

  def destroy
    update(deleted: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if user_signed_in?

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    authorize @comment, :owner?
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    authorize @comment, :owner?
    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    authorize @comment, :owner?
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper PostsHelper

  def index
    # Select 3 posts within last 2 days with highest trending score
    day_limit = 2
    num_post = 3
    @posts = Post
             .select { |post| post['created_at'] >= Time.zone.today - day_limit.day }
             .sort_by(&:compute_trending_score)
             .last(num_post)
             .reverse
    existing_post_num = @posts.length
    return unless existing_post_num < num_post
    # Fill the remaining slots with most recent posts
    most_recent_posts = Post.where.not(id: @posts.map(&:id))
                            .order('created_at')
                            .last(num_post - existing_post_num)
                            .reverse
    @posts += most_recent_posts

    @footer_links =
      [
        {
          link: 'forum',
          title: 'Forum',
          description: 'Engage with your peers!',
        },
        {
          link: '#link',
          title: 'Articles',
          description: 'Read stories and learn the basics about your body!',
        },
        {
          link: '#link',
          title: 'Get Help',
          description: 'Find a clinic in your area!',
        },
        {
          link: 'mailto:info@helplesotho.org',
          title: 'Contact Us',
          description: 'Get in touch with the Help Lesotho Foundation',
        },
      ].freeze
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show search]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    authorize @post, :owner?
  end

  def update
    authorize @post, :owner?
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    authorize @post, :owner?
    @post.destroy
    redirect_to root_path
  end

  def search
    params.permit(:query)
    @query = params[:query]
    @posts = Post.where('title ILIKE ? OR content ILIKE ?', "%#{@query}%", "%#{@query}")
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    if current_user.admin?
      params.require(:post).permit(:title, :content, :featured)
    else
      params.require(:post).permit(:title, :content)
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def truncate_content(content)
    truncate(content, length: 87)
  end
end

app/views/admin/index.slim
h1

app/views/comments/_comment.slim
div
  p= comment.comment
  p= comment.user.email
  - if current_user.present? && (comment.user_id == current_user.id || current_user.admin)
  	= link_to "Edit", edit_post_comment_path(comment.post, comment)
  - if current_user.present? && (comment.user_id == current_user.id || current_user.admin)
  	= button_to "Delete Reply", [comment.post, comment], method: :delete

app/views/comments/_form.slim
= simple_form_for([@post, @post.comments.build]) do |f|
  = f.input :comment
  = f.submit

app/views/comments/edit.slim
h1 Edit Reply

= simple_form_for([@post, @comment]) do |f|
  = f.input :comment
  = f.submit

app/views/home/index.slim
section.card.card-2.mx1.mb1
  h1.card-divider.h3.m0.p2.regular.center What are people talking about in Lesotho?

  - if @posts.empty?
    h2 There aren't any posts yet
  - else
    ul.list-reset.m0
      - @posts.each do |post|
        li
          a.card-divider.block.text-decoration-none.py2 href="#{post_path(post)}"
            div.table-cell.align-middle.px1
              img.circle.user-icon src="https://i.pinimg.com/564x/7c/c7/a6/7cc7a630624d20f7797cb4c8e93c09c1.jpg"
            div.table-cell.align-middle.pr1
              h5.h5.m0.card-listItem-header=post.title
              p.m0.card-listItem-text=truncate_content(post.content)

  div.right-align.py2.pr2
    a.btn.btn-secondary.mr2 Visit Forum
    button.btn Join The Community

section#HomeSearchComponent.homeSearch.card.card-2.mx1.mtn1.mb1.__react-root

section.card.card-2.mx1.mb1
  h1.card-divider.h4.m0.p2.regular.left-align Featured Posts
  - if @posts.empty?
    h2 There aren't any posts yet
  - else
    ul.list-reset.m0
      - @posts.each do |post|
        li.two-col
          div.a.card-divider.block.text-decoration-none.py2 href="#{post_path(post)}"
            div.table-cell.featured-posts.px1
              h5.h5.m0.card-listItem-header=post.title
              p.m0.card-listItem-text=truncate_content(post.content)

section.footer.mx1.mb1
  ul.list-reset.h6
    - @footer_links.each do |item|
      li
        a.block.text-decoration-none href=item[:link]
          div.table-cell.align-middle.px1
            img.arrow-icon src=asset_pack_path('right-arrow.png')
          div.table-cell.align-middle.pr1
            h5.m0.footer-listItem-header=item[:title]
            p.m0.footer-listItem-text=item[:description]

app/views/layouts/application.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    title Help Lesotho
    = csrf_meta_tags
    = stylesheet_pack_tag "application"

    - if Rails.env.production?
      = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css"
      = stylesheet_link_tag "https://unpkg.com/basscss@8.0.2/css/basscss.min.css"
    - else
      = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.css"
      = stylesheet_link_tag "https://unpkg.com/basscss@8.0.2/css/basscss.css"

  body.u-widthWrapper
    header
      = content_tag :div,                   \
        id: "NavBarComponent",              \
        class: "__react-root",              \
        data: {                             \
          logged_in: (current_user != nil)  \
        }.to_json do

      p.notice.m0= notice
      p.alert.m0= alert

      - if current_user != nil
        = link_to "New Post", new_post_path

    = yield

    - if request.path.start_with?("/admin")
      = javascript_pack_tag "admin"
    - else
      = javascript_pack_tag "application"

app/views/posts/_form.slim
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  - if @current_user.admin?
    = f.input_field :featured, as: :boolean
  = f.submit

app/views/posts/edit.slim
h1 Edit

= render "form"
= link_to "Cancel", post_path

app/views/posts/index.slim
- @posts.each do |post|
  h2= link_to post.title, post
  div= "Published " + time_ago_in_words(post.created_at) + " ago"
  div= "By " + post.user.email

= link_to "New Post", new_post_path

app/views/posts/new.slim
h1 hello world

= render 'form'

app/views/posts/search.slim
section
  - if @posts.empty?
    h2= "No posts found for #{@query}"
  - else
    - @posts.each do |post|
      div
        h2= link_to post.title, post
        div= "Published " + time_ago_in_words(post.created_at) + " ago"
        div= "By " + post.user.email

app/views/posts/show.slim
h1= @post.title
p= @post.content

// Comments
div
  h3= "Number of comments: " + @post.comments.count.to_s
  = render @post.comments

  h3 Reply to thread
  = render "comments/form"

- if current_user.present? && (current_user.id == @post.user_id || current_user.admin)
	= link_to "Edit", edit_post_path(@post)
- if current_user.present? && (current_user.id == @post.user_id || current_user.admin)
	= button_to "Delete", post_path(@post), method: :delete

= link_to "Home", root_path